services:
  tests:
    build: .
    image: playwright-e2e
    init: true
    ipc: host
    environment:
      - BASE_URL=${BASE_URL:-https://markolosic.github.io}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
